### ISSUE TITLE
remove old Test::Unit backwards compatible API

### ISSUE THREAD

**Issue by kellyredding** [redding/assert#244]
Test::Unit is pretty dated by now.  I don't see value in keeping this available in Assert's API.  It would remove a good bit of code and special handling too.

@jcredding what do you think about this?  Related to #242.

**Comment by jcredding** [comment]
@kellyredding - I'm fine with doing this. We haven't used it or needed it. I think we've opted to rewrite tests rather than try to get old test-unit tests running with assert.

**Comment by kellyredding** [comment]
FYI, Minitest still supports/refers to it: https://github.com/seattlerb/minitest#unit-tests

**Comment by kellyredding** [comment]
Closed b/c of #303
